### ISSUE TITLE
Manipulator + GIS Widget

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#101]
https://github.com/DeMarcoLab/fibsem/pull/88

**MANIPULATOR WIDGET**
- [x] XYZ controls
- [x] insert/retract button
- [x] insert position combobox
- [x] add park and eucentric positions (THERMO)
- [ ] Manipulator Status (inserted/not inserted)
- [ ] Safety / Validation check
- [x] Add relative move

**GIS WIDGET**
- [x] Insert position combobox
- [x] insert/retract button
- [x] Gas selection
- [ ] Time duration selection
- [ ] Application file (THERMO)
- [ ] Beam type
- [ ] HFW
- [ ] Blank Beam (checkbox)
- [ ] Run button
- [ ] Patterns 

- [ ] **Create documentation showing difference in behaviour for manufacturers (GIS)**

**Comment by Rohit-Kannachel** [comment]
Changes to Manipulator Widget

- movement in microns instead of mm
- removed absolute movement
- added corrected move for thermo including beam type
- removed tilt movement as it is not supported

Changes to GIS Widget

- Removed from UI for now, still WIP
