### ISSUE TITLE
Current issues with autolamella example on v0.2-stable

### ISSUE THREAD

**Issue by sroet** [DeMarcoLab/fibsem#117]
I tried to run the autolamella example on commit https://github.com/DeMarcoLab/fibsem/commit/e3deb2b53360933115b87940daa556359a628735 (current head of v0.2-stable) and ran into the following issues:

- `state.ib_settings.resolution`/`state.eb_settings.resolution` should be mapped back to the string `f'[0]x[1]'` before feeding it to the microscope, as our autoscript install will only process strings and not lists as valid values to set.
- `protocol_autolamella.yaml` is missing a key `depth` for each of the lamella protocol stages. Is this a rename of `milling_depth`? (copying those values seemed to work)
- During the milling, the example is is not moving the stage: The line `microscope.set_microscope_state(lamella.state)` does not update the positions, so I had to add  `microscope.move_stage_absolute(lamella.state.absolute_position)` before that line.

I am sorry if any/all of these issues are already fixed on the dev branch, I did not have time to check that out. Feel free to close if that is the case.

After some hacks to fix these issues, I got the example to run successfully. 
Edit in case it matters: This is on a Thermo microscope

**Comment by patrickcleeve2** [comment]
hey @sroet you are correct on all three, we've just pushed a fix onto 0.2-dev (https://github.com/DeMarcoLab/fibsem/commit/64a984f28fd063e9ad2290e9a10202b5e97bf471) if you want to try again.

We also have a more fully fleshed out autolamella if you are interested: https://github.com/DeMarcoLab/autolamella.

Thanks again
