### ISSUE TITLE
[FEAT] Manipulator Insert / Retract (TESCAN)

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#138]
Abstract the TESCAN positions to unify with THERMO:

Parking == Retracted
Standby == Inserted

microscope.insert_manipulator should move the needle from PARKING -> STANDBY
microscope.retract_manipulator should move the needle from current position -> STANDBY -> PARKING

Should feel the same as the THERMO system to the external user.

**Comment by Rohit-Kannachel** [comment]
Write up docs detailing how the manipulator calibration tool works and why it is doing it
