### ISSUE TITLE
[MIGRATE] Model.yaml -> System.yaml

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#157]
migrate the model.yaml into the system.yaml

Now that we have ui, and arent really expecting the user to edit this manually we should merge these two files together

**Comment by patrickcleeve2** [comment]
update manipulator calibration
https://github.com/DeMarcoLab/fibsem/blob/fd20bed3d0754d2d6433a87681a50ab06d88e764/fibsem/ui/FibsemManipulatorWidget.py#L154

**Comment by LucileNaegele** [comment]
manipulator calibration fixed

**Comment by patrickcleeve2** [comment]
@LucileNaegele  @Rohit-Kannachel has this been resolved?
