### ISSUE TITLE
[UI] Tab Order

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#184]
We need to go through and clean up the tab order for each widget, its pretty random and annoying atm

**Comment by Rohit-Kannachel** [comment]
- [x] System Widget
- [x] Image Settings Widget
- [x] Movement Widget
- [x] Milling Widget
- [x] Hardware Settings
- [x] Manipulator Widget
- [x] Current Alignment Widget
- [x] Detection Widget
