### ISSUE TITLE
[UI] User Interface Consistency

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#193]
The UI is very inconsistent in terms of font size, spacing, ordering. We need to make this much more consistent because it causes issues with usability.

Main issues:
Aesthetics: 
- when colouring buttons we need to implmement the :hover property as well (see autolamella._stylesheets) so users know they can click it.
- sizing: so many things are different sizes that shouldnt be
- lots of missing / redundant headers. we need to decide when we use a header / when we dont
- tabception is becoming a problem; what are some solutions

Consistency
- ordering should be consistent; e.g. electron on left, ion on right 
- tab order is completely broken
- func, variable names inaccurate, mismatched

Feedback
- needs to provide user more feedback  (e.g. notifications). example is when we are imaaging or moving as this can take a while to resolve (e.g. TESCAN)
- Disabling functionality when not allowed.

**Comment by LucileNaegele** [comment]
- [x] System Widget
- [x] Image Settings Widget
- [x] Movement Widget
- [x] Milling Widget
- [x] Manipulator Widget
- [x] Current Alignment Widget
- [x] Detection Widget
