### ISSUE TITLE
No sdist available to download to be able to build a conda forge recipe

### ISSUE THREAD

**Issue by goanpeca** [DeMarcoLab/fibsem#313]
Hello team, while trying to create a conda recipe on conda forge for this package, we noticed that there are no sdist available on the pypi page

No sdist available to download to be able to build a conda forge recipe

https://pypi.org/project/fibsem/#files

The source code (sdist) is required to be able to create a conda package.

Could you upload this?

**Comment by patrickcleeve2** [comment]
hi @goanpeca, sdist should be available for the latest release v0.3.1. thanks!
