### ISSUE TITLE
[BUG] Reduced Area not unset correctly

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#74]
Manufacturer: Thermo Fisher

When imaging with Image_settings.reduced_area = None, this does not set the imaging to full area imaging. This means that if reduced area has been selected in the UI, this setting will not be applied correctly.

Should explicitly set the condition as the system will use whatever is chosen in the UI if not explicitly set.

**Comment by LucileNaegele** [comment]
need to test fix

**Comment by patrickcleeve2** [comment]
@LucileNaegele was this closed?

**Comment by LucileNaegele** [comment]
@patrickcleeve2  we haven't tested it yet but the code is there
