### ISSUE TITLE
[FEAT] Manufacturer / Model / Serial No. Info

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#76]
Add method to get the relevant manufactuer, model, serial id for the system automatically. 
- Maybe assist with defining the model.yaml automatically

- [x] model
- [x] serial number
- [x] software version

**Comment by LucileNaegele** [comment]
take 1x1 i8mage for tescan for metadata

**Comment by LucileNaegele** [comment]
getting model & serial number
