### ISSUE TITLE
[FEAT] Add support for live imaging

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#82]
Add support for live imaging
- should be threaded, and use an image queue to read the buffer

**Comment by LucileNaegele** [comment]
CHECK WITH THE BOSS

**Comment by patrickcleeve2** [comment]
Need to disable taking images after movement when live imaging. Should return to previous setting when finished

**Comment by LucileNaegele** [comment]
- [ ] enable click to move
