### ISSUE TITLE
[UI] Measurement Tools

### ISSUE THREAD

**Issue by patrickcleeve2** [DeMarcoLab/fibsem#84]
Add measurement tools to UI
-  [x] working scale bar
- [ ] measurement drawing tool (line)

**Comment by Rohit-Kannachel** [comment]
scale bar is currently 20% the size of screen, maybe a dynamic round number scale bar would be better?

**Comment by patrickcleeve2** [comment]
@Rohit-Kannachel  check out how this was done in openlm: can use inbuilt napari scalebar

https://github.com/DeMarcoLab/openCLEM/blob/9fb5873b79cd73a16225e460591f7093aabc934a/openlm/ui/OpenLMImageWidget.py#L197

**Comment by Rohit-Kannachel** [comment]
In detection widget there is dynamic measuring tape
